---
- name: Import CrowdStrike Falcon system package GPG key
  block:
    # The Fedora 41 Docker container we use for Molecule testing does
    # not have GPG installed by default.
    - name: Install gpg
      ansible.builtin.package:
        name:
          - gnupg2
      when:
        - ansible_distribution == "Fedora"

    - name: Grab CrowdStrike Falcon system package GPG key from S3
      amazon.aws.s3_object:
        bucket: "{{ crowdstrike_third_party_bucket_name }}"
        dest: /tmp/{{ package_gpg_key_object_name }}
        mode: get
        object: "{{ package_gpg_key_object_name }}"
      become: false
      delegate_to: localhost

    - name: Copy the CrowdStrike Falcon system package GPG key
      ansible.builtin.copy:
        dest: /tmp/{{ package_gpg_key_object_name }}
        mode: 0700
        src: /tmp/{{ package_gpg_key_object_name }}

    - name: Import CrowdStrike Falcon system package GPG key
      ansible.builtin.rpm_key:
        key: /tmp/{{ package_gpg_key_object_name }}

- name: Install CrowdStrike Falcon (RedHat)
  ansible.builtin.dnf:
    name:
      - /tmp/{{ package_file }}

- name: Delete copies of CrowdStrike Falcon system package GPG key
  block:
    - name: Delete local copy of CrowdStrike Falcon system package GPG key
      ansible.builtin.file:
        path: /tmp/{{ package_gpg_key_object_name }}
        state: absent
      become: false
      delegate_to: localhost

    - name: Delete remote copy of CrowdStrike Falcon system package GPG key
      ansible.builtin.file:
        path: /tmp/{{ package_gpg_key_object_name }}
        state: absent
